owner: juanbarreamonsalve
repo: status-page

# Tus sitios a monitorear
sites:
  - name: Mantum Admin
    url: https://admin.cloudmantum.com.co/mantum/publico/auth/login/
    
  - name: Mantum Comercial
    url: https://comercial.cloudmantum.com/mantum/publico/auth/login/
    
  - name: Mantum v223
    url: https://v223.cloudmantum.com/mantum/publico/auth/login/

# Configuración de la página visual
status-website:
  # ¡IMPORTANTE! cname debe ser null para evitar el error de dominio
  cname: null
  
  name: Estado CloudMantum
  introTitle: "**Estatus de Servicios**"
  introMessage: "Monitoreo en tiempo real de las plataformas Mantum."
  
  # Tu logo (Asegúrate de que el nombre del archivo sea exacto)
  logoUrl: https://raw.githubusercontent.com/juanbarreamonsalve/status-page/main/camilobarreramonsalve-png
  
  navbar:
    - title: Status
      url: /
    - title: GitHub
      url: https://github.com/$OWNER/$REPO

# Frecuencia de actualización (No tocar)
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
