AML

owner: TuUsuarioDeGitHub # <--- ¡IMPORTANTE! Cambia esto por tu usuario real
repo: estado-core        # <--- El nombre que le pusiste a tu repositorio

sites:
  - name: Mantum Admin
    url: https://admin.cloudmantum.com.co/mantum/publico/auth/login/
    
  - name: Mantum Comercial
    url: https://comercial.cloudmantum.com/mantum/publico/auth/login/
    
  - name: Mantum v223
    url: https://v223.cloudmantum.com/mantum/publico/auth/login/

  # Esta es la página rota de prueba (dará error intencionalmente)
  - name: Prueba de Error
    url: https://google.com/esta-pagina-no-existe-error-404

status-website:
  name: Estado de CloudMantum
  introTitle: "**Estatus de Servicios**"
  introMessage: "Monitoreo en tiempo real de las plataformas Mantum."
  navbar:
    - title: Status
      url: /
    - title: GitHub
      url: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
