# ==========================================
# CONFIGURACIÓN GENERAL
# ==========================================
owner: juanbarreamonsalve
repo: status-page

# ==========================================
# TUS SITIOS A MONITOREAR
# ==========================================
sites:
  - name: Mantum Admin
    url: https://admin.cloudmantum.com.co/mantum/publico/auth/login/
    
  - name: Mantum Comercial
    url: https://comercial.cloudmantum.com/mantum/publico/auth/login/
    
  - name: Mantum v2231
    url: https://v223.cloudmantum.com/mantum/publico/auth/login/

  # SITIO DE PRUEBA (Para ver el error rojo)
  - name: Prueba de Fallo
    url: https://google.com/esta-pagina-no-existe-error-404

# ==========================================
# DISEÑO DE LA PÁGINA WEB
# ==========================================
status-website:
  # CNAME debe ser null estrictamente
  cname: null
  
  # Título en la pestaña del navegador
  name: Estado Mantum
  
  # Textos de la portada (Entre comillas para evitar errores)
  introTitle: "Bienvenidos al uptime de Mantum"
  introMessage: "Monitoreo en tiempo real de la disponibilidad de nuestros servicios."
  
  # Tu logo
  logoUrl: https://raw.githubusercontent.com/juanbarreamonsalve/status-page/main/camilobarreramonsalve-png
  
  # Menú de navegación superior
  navbar:
    - title: Estado
      url: /
    - title: Ir a Mantum Comercial
      url: https://mantum.com.co/

# ==========================================
# HORARIOS (NO TOCAR)
# ==========================================
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
