# Configuración del Repositorio
owner: juanbarreamonsalve
repo: status-page

# Tus sitios a monitorear
sites:
  - name: Mantum Admin
    url: https://admin.cloudmantum.com.co/mantum/publico/auth/login/
    
  - name: Mantum Comercial
    url: https://comercial.cloudmantum.com/mantum/publico/auth/login/
    
  - name: Mantum v223
    url: https://v223.cloudmantum.com/mantum/publico/auth/login/

  # SITIO DE PRUEBA (Dará error intencional para ver el color rojo)
  - name: Prueba de Fallo
    url: https://google.com/esta-pagina-no-existe-error-404

# Configuración visual de la página
status-website:
  # CNAME debe ser null
  cname: null
  
  # Título de la pestaña
  name: Estado Mantum
  
  # Textos de bienvenida personalizados
  introTitle: "Bienvenidos al uptime de Mantum"
  introMessage: "Monitoreo en tiempo real de la disponibilidad de nuestros servicios."
  
  # Tu logo
  logoUrl: https://raw.githubusercontent.com/juanbarreamonsalve/status-page/main/camilobarreramonsalve-png
  
  # Menú superior con redirección a la web comercial
  navbar:
    - title: Estado
      url: /
    - title: Ir a Mantum Comercial
      url: https://mantum.com.co/

# Frecuencia de actualización
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
